### ISSUE TITLE
Junção de projetos

### ISSUE THREAD

**Issue by hyanmandian** [VitorLuizC/brazilian-values#1]
Opa, tudo certinho? Sou um dos criadores da brazilian-utils (https://github.com/brazilian-utils/brazilian-utils) e eu achei muito interessante o teu projeto.

Queria te convidar para fazer parte da nossa organização e incorporar tuas lib a nossa toolkit, o que você acha disso? Contamos hoje com 5 contribuidores ativos e seria incrível te ter como parte dessa equipe :smile:

**Comment by VitorLuizC** [comment]
Eu fico muito contente pelo convite e já tinha visto o projeto de vocês antes, cheguei até a navegar pelos fontes, e como não encontrei definições de tipos e algumas decisões divergiram do que eu estava procurando decidi fazer eu mesmo as funcionalidades que eu precisava. Podemos conversar mais a respeito e posso te explicar os detalhes dessa decisão.

Falando um pouco do `brazilian-values`, ele é uma _fork_ de um punhado de utilitários que usava na Convenia com Vue, o [`vue-convenia-util`](https://github.com/convenia/vue-convenia-util). Bom, como não estou trabalhando com Vue, resolvi desacoplar e refatorar os formatadores e validações num módulo mais genérico e útil.

**Comment by hyanmandian** [comment]
Se tu poder ser mais específico, eu ficaria mt grato de ouvir e melhorar a nossa lib com sugestões tuas :smile: 
Caso esteja interessado em conversar melhor sobre o convite, pode me procurar no Facebook e continuamos nossa conversa por lá.

**Comment by VitorLuizC** [comment]
Vou fazer isso mesmo, é mais fácil conversar por lá. E, cara, eu realmente acho interessante juntar os projetos, só quero entender melhor ele e como contribuir de forma eficiente

**Comment by VitorLuizC** [comment]
Fechei porque já conversamos no Facebook e ficou decidido que vou contribuir com o `brazilian-utils` quando possível, porém o `brazilian-values` não será depreciado.
