### ISSUE TITLE
Missing isCEP()

### ISSUE THREAD

**Issue by ganobrega** [VitorLuizC/brazilian-values#15]

**Comment by VitorLuizC** [comment]
Li um pouco sobre validações e encontrei um repositório com propósito similar ao brazilian-values em Golang que implementa essa validação.

https://github.com/Nhanderu/brdoc/blob/master/cep.go

A validação consiste no valor ter 8 caracteres numéricos, ignorando traços e pontos e opcionalmente com a checagem dos primeiros caracteres por UF.

```js
isCEP('02912030', 'SP');
//=> true

isCEP('02912030');
//=> true

isCEP('02912-030', 'SP');
//=> true

isCEP('02912-030', 'RJ');
//=> false
```

**Comment by VitorLuizC** [comment]
Aliás, não estou encontrando de onde vem esses _ranges_ dos estados. Procurei bastante e só encontrei respostas em fórums de Java e Delphi, sem nenhuma fonte...

Acho que vou fazer como o brazilian-utils e o cep-promise que só validam a quantidade de dígitos.

**Comment by VitorLuizC** [comment]
Implementei o validador de CEP, porém não tem os _ranges_ dos estados por falta de documentação ou fonte confiável. Se for o caso deles serem importantes para você peço que abra um novo issue e se quiser pode até referenciar este
