### ISSUE TITLE
Telefones

### ISSUE THREAD

**Issue by giulianon** [VitorLuizC/brazilian-values#19]
Muito boa esse lib.
Sugiro uma validação para os telefones também.

**Comment by VitorLuizC** [comment]
Pensei bastante em como fazer validação de telefone/celular de uma forma eficiente e consegui fazer validando o formato (com DDI, DDD e o nono dígito opcionais) e validando o DDD quando disponível.

Pro DDD tive que fazer uma pesquisa e achar a resolução que define quais os DDDs válidos.

**Comment by VitorLuizC** [comment]
Bom, finalizei no commit https://github.com/VitorLuizC/brazilian-values/commit/3fe0d53f3e723a0ae3fa48e8b4a8c42549121016 e publiquei agora pouco a versão [0.6.0](https://github.com/VitorLuizC/brazilian-values/releases/tag/0.6.0) com isso.
