### ISSUE TITLE
Capitalize

### ISSUE THREAD

**Issue by ymoreiratiti** [VitorLuizC/brazilian-values#20]
Incoporar uma função de Capitalize, similar ao 
https://www.npmjs.com/package/capitalize-pt-br

Vantagem:
* Unificação de função no mesmo package

Me disponibilizo a fornecer um pull request

**Comment by VitorLuizC** [comment]
Me parece bastante interessante e dentro do que o **brazilian-values** se propõe em atender. Porém, precisa ser algo implementado dentro do **brazilian-values** porque essa lib não tem arquivos de definições de tipos para TypeScript e só disponibiliza módulos CommonJS.
