### ISSUE TITLE
split date de um formato que é padrão em alguns bancos

### ISSUE THREAD

**Issue by Aleceler** [VitorLuizC/brazilian-values#22]
eu resolvi splitando no meu projeto, mas seria legal fazer esse split por aqui talvez, se quiser eu posso contribuir :), valeuee

segue o formato: '2019-11-27T19:00:00Z'

**Comment by VitorLuizC** [comment]
Acho que foge do propósito da biblioteca. As funções do `brazilian-values` se comprometem apenas em formatar, converter e validar valores, unidades e documentos brasileiros.

Talvez o que dê para fazer é melhorar o [`parseToDate`](https://github.com/VitorLuizC/brazilian-values#parsetodate) para receber também o formato com horas, minutos e segundos e deixar pro consumidor da biblioteca transformar a data nativa com [`Date.prototype.toISOString()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toISOString).

Ex.

```ts
import { parseToDate } from 'brazilian-values';

// ...

const save = async (formattedDate: string) => {
  try {
    const date = parseToDate(formattedDate);
    await saveToDatabase(date.toISOString());
  } catch (error) {
    // ...
  }
};
```

**Comment by VitorLuizC** [comment]
Abri a issue #23 para implementar o suporte a data e hora no `parseToDate`.

**Comment by VitorLuizC** [comment]
Fechei em favor da #23.
