### ISSUE TITLE
Why not use toLocaleString in formatToBRL?

### ISSUE THREAD

**Issue by mathvaleriano** [VitorLuizC/brazilian-values#25]
You could use `value.toLocaleString('pt-br', { style: 'currency', currency: 'BRL' })`.
What do you think about it?
Thanks a lot for this lib 💯

**Comment by VitorLuizC** [comment]
`brazilian-values` is compatible with ES5 and in its spec the `.toLocaleString` works exactly like `.toString`.

O `brazilian-values` é compatível com ES5 e nele o `.toLocaleString` é exatamente igual ao `.toString`.

https://www.ecma-international.org/ecma-262/5.1/#sec-15.7.4.3

**Comment by lpj145** [comment]
cumulo do absurdo, pacote é de um brasileiro, é sobre o brasil, sobre nosso idioma, moeda, características, abre issue em inglês, é respondido em inglês....

**Comment by lpj145** [comment]
e pra piorar to eu aqui, só criticando....

**Comment by VitorLuizC** [comment]
Acontece asuhauhshuahushua

**Comment by VitorLuizC** [comment]
A gente entra no papel de dev e não consegue sair quando é num contexto que pode falar em português aushauhshuauhs
