### ISSUE TITLE
Include a new format of cep

### ISSUE THREAD

**Issue by mathvaleriano** [VitorLuizC/brazilian-values#26]
In isCep function when I verify with this format ##.###-### it will return me a false, but if I use the same value without the mask it will be ok.
So could you use at the cep pattern an optional '.' and '-'

**Comment by VitorLuizC** [comment]
Right now `isCEP` accepts 8 digits or 99999-999 format as valid.

I'll add `##.###-###` as valid format too.

**Comment by VitorLuizC** [comment]
Fixed and published on https://github.com/VitorLuizC/brazilian-values/releases/tag/0.7.2.
