### ISSUE TITLE
Adicionar função que formate o valor para CPF ou CNPJ (dependendo da largura)

### ISSUE THREAD

**Issue by VitorLuizC** [VitorLuizC/brazilian-values#28]
É comum encontrar aplicações que usem um único campo como CNPJ ou CPF. E exportar uma função que faça isso automaticamente será bastante útil.

**Comment by mandala21** [comment]
se nao tiver implementado, eu posso fazer.

**Comment by VitorLuizC** [comment]
@mandala21 poxa, ia ser bem massa! Agradeço muito se você puder fazer.

**Comment by mandala21** [comment]
fiz a PR. Tive um problema com o meu ambiente local, meu node era 8 e o projeto request 12 então criei um amibente no Docker. Posso fazer a PR dele tambem se interresar. Coloquei umas informações no README sobre o docker no branch docker do meu fork

**Comment by VitorLuizC** [comment]
Me interessa bastante ter um ambiente com Docker, sim!  Vou abrir outra _issue_ para isso e levar a discussão para lá.

A PR #29 eu mergeei e já já publico uma nova versão no NPM com ela. Assim que eu publicar já fecho essa issue.

**Comment by VitorLuizC** [comment]
Prontinho! Publiquei a versão [`0.7.4`](https://github.com/VitorLuizC/brazilian-values/releases/tag/0.7.4) com a mudança.

**Comment by mandala21** [comment]
@VitorLuizC certo, fico no aguardo da issue do docker
