### ISSUE TITLE
Adicionar um ambiente docker para contribuidores

### ISSUE THREAD

**Issue by VitorLuizC** [VitorLuizC/brazilian-values#30]
> fiz a PR. Tive um problema com o meu ambiente local, meu node era 8 e o projeto request 12 então criei um amibente no Docker. Posso fazer a PR dele tambem se interresar. Coloquei umas informações no README sobre o docker no branch docker do meu fork
>
> _Originally posted by @mandala21 in https://github.com/VitorLuizC/brazilian-values/issues/28#issuecomment-586614221_

**Comment by mandala21** [comment]
vou fazer a PR do ambiente, adicionei no readme uma pequena introdução, não sei se esta bom kkkkkk. 

Estou tambem com um problema que precisa executar um npm install ou um yarn install antes de executar os comandos do packed.json

**Comment by VitorLuizC** [comment]
Já foi adicionado e me esqueci de fechar a _issue_.
