### ISSUE TITLE
Mixed valid isCPF with isCPNJ 

### ISSUE THREAD

**Issue by selique** [VitorLuizC/brazilian-values#40]
request the merge funcionality isCPF with isCPNJ for validation

**Comment by VitorLuizC** [comment]
If is something like checking if is either CPF or a CNPJ, @roziscoding added it yesterday and I published under version 0.9.0.

---

Se for algo como checar se é um CPF ou um CNPJ, o @roziscoding adicionou isso ontem e eu publiquei na versão 0.9.0.

---

```js
import { isCPFOrCNPJ } from 'brazilian-values'

isCPFOrCNPJ('366.418.768-70')
//=> true

isCPFOrCNPJ('45.723.174/0001-10')
//=> true

isCPFOrCNPJ('411407182')
//=> false

isCPFOrCNPJ('11.111.111/1111-11')
//=> false
```

https://github.com/VitorLuizC/brazilian-values/releases/tag/0.9.0

**Comment by VitorLuizC** [comment]
Can I close this issue?

<details>
<summary>Em português</summary>

Eu posso fechar essa _issue_?
</details>
