### ISSUE TITLE
fix command formatBRL in npm README

### ISSUE THREAD

**Issue by nicholasess** [VitorLuizC/brazilian-values#5]
Please, fix command in README from npm, you need to publish again with fix.

https://www.npmjs.com/package/brazilian-values#formattobrl

**Comment by VitorLuizC** [comment]
Sorry about that, I fixed the same typo on `formatToBRL` TSDocs and everything will be published under the 0.3.0 version.

**Comment by VitorLuizC** [comment]
https://github.com/VitorLuizC/brazilian-values/releases/tag/0.3.0
